[general]
import = ["themes/gruvbox_material_medium_dark.toml"]

[window]
decorations = "none"
startup_mode = "Maximized"

[font]
size = 19.5
normal = { family = "MesloLGM Nerd Font", style = "Regular" }

[cursor.style]
blinking = "Never"

[terminal.shell]
program = "mise"
args = ["exec", "--", "zellij"]

[keyboard]
bindings = [{ key = "Return", mods = "Shift", chars = "\u001b\r" }]
