[general]
import = ["~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"]

[window]
startup_mode = "Maximized"

[font]
size = 19.5
normal = { family = "MesloLGM Nerd Font", style = "Regular" }

[cursor.style]
blinking = "Never"

[shell]
program = "zellij"

[keyboard]
bindings = [{ key = "Return", mods = "Shift", chars = "\u001b\r" }]
