[general]
import = [ "~/.config/alacritty/themes/themes/ayu_dark.toml" ]

[font]
size = 12
normal = { family = "MesloLGM Nerd Font", style = "Regular" }

[terminal]
shell = { program = "zellij" }

[keyboard]
bindings = [ { key = "Return", mods = "Shift", chars = "\u001b\r" } ]
