set number             " Show line numbers
set tabstop=4          " Tab width
set shiftwidth=4       " Indent width
set nowrap             " Disable wrapping
set noruler            " Disable ruler
set fillchars+=eob:\   " Hide `~` on empty lines past end of buffer
