theme = "ly-theme"

[editor]
mouse = false
insert-final-newline = false

[editor.gutters]
layout = ["spacer", "line-numbers", "spacer", "diff"]

[editor.gutters.line-numbers]
min-width = 1

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1

[editor.lsp]
display-inlay-hints = true

[editor.statusline]
right = [
  "diagnostics",
  "register",
  "file-encoding",
  "file-line-ending",
  "file-type"
]
mode.normal = "N"
mode.insert = "I"
mode.select = "S"

[keys.normal]
C-s = ":w"  # Ctrl-s (save file)
C-y = [
  ":sh rm -f /tmp/unique-ca1ea106",
  ':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/unique-ca1ea106',
  ':sh printf "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ":open %sh{cat /tmp/unique-ca1ea106}",
  ":redraw",
]
C-r = ":reload-all"

[keys.normal.space]
"=" = ":format"

[keys.normal.g]
a = "code_action"  # Maps `ga` to show possible code actions

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"
