theme = "akari-night"

[editor.gutters]
layout = ["spacer", "line-numbers", "spacer", "diff"]

[editor.gutters.line-numbers]
min-width = 1

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1

[editor.statusline]
right = ["diagnostics", "selections", "register", "file-encoding", "file-line-ending", "file-type"]
mode.normal = "N"
mode.insert = "I"
mode.select = "S"

[keys.normal.C-y]
# Open the file(s) in the current window
y = ":sh zellij run -n Yazi -c -f -x 10%% -y 10%% --width 80%% --height 80%% -- bash ~/.config/helix/yazi-picker.sh open %{buffer_name}"
# Open the file(s) in a vertical split
v = ":sh zellij run -n Yazi -c -f -x 10%% -y 10%% --width 80%% --height 80%% -- bash ~/.config/helix/yazi-picker.sh vsplit %{buffer_name}"
# Open the file(s) in a horizontal split
h = ":sh zellij run -n Yazi -c -f -x 10%% -y 10%% --width 80%% --height 80%% -- bash ~/.config/helix/yazi-picker.sh hsplit %{buffer_name}"
