# [language-server.uwu_colors]
# command = "uwu_colors"

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.ty]
command = "ty"
args = ["server"]

[[language]]
name = "python"
language-servers = ["ruff", "ty"]
auto-format = true

[[language]]
name = "toml"
language-servers = ["tombi"]

# [[language]]
# name = "kdl"
# language-servers = [{ name = "uwu_colors" }]

[[language]]
name = "markdown"
comment-tokens = ["-", "+", "*", "1.", ">", "- [ ]"]

[[language]]
name = "bash"
indent = { tab-width = 4, unit = "    " }
