[settings]
minimum_release_age_excludes = ["claude"]

[tools]
bat = "latest"
bats = "latest"
caddy = "latest"
cargo-binstall = "latest"
"cargo:systemd-lsp" = "latest"
claude = "latest"
fastfetch = "latest"
fd = "latest"
fzf = "latest"
jq = "latest"
lazygit = "latest"
"npm:bash-language-server" = "latest"
"npm:skills" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:yaml-language-server" = "latest"
oh-my-posh = "latest"
opentofu = "latest"
rust = "stable"
shellcheck = "latest"
terraform-ls = "latest"
tombi = "latest"
usage = "latest"
yazi = "latest"
zellij = "latest"
yamlfmt = "latest"
codex = "latest"

[tools."cargo:https://github.com/helix-editor/helix"]
version = "branch:master"
crate = "helix-term"
